# Generated by Django 5.2.17 on 2026-09-21 00:30

import django.db.models.deletion
from django.db import migrations, models


def migrate_exam_questions_to_categories(apps, schema_editor):
    ExamQuestion = apps.get_model("exams", "ExamQuestion")
    ExamCategory = apps.get_model("exams", "ExamCategory")
    counts = {}
    for exam_id, category in ExamQuestion.objects.values_list(
        "exam_id", "question__category"
    ):
        key = (exam_id, category)
        counts[key] = counts.get(key, 0) + 1
    ExamCategory.objects.bulk_create(
        ExamCategory(exam_id=exam_id, category=category, question_count=count)
        for (exam_id, category), count in counts.items()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('vocabulary', 'Vocabulary in Context'), ('grammar', 'Grammar Challenge'), ('expression', 'Functional Expression'), ('reading', 'Reading Comprehension'), ('cloze', 'Cloze Test'), ('sentence', 'sentence arrangement and logic'), ('synonym_antonym', 'Synonym Antonym Formation'), ('hots', 'HOTS & Olympiad Challenge')], default='vocabulary', max_length=20),
        ),
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vocabulary', 'Vocabulary in Context'), ('grammar', 'Grammar Challenge'), ('expression', 'Functional Expression'), ('reading', 'Reading Comprehension'), ('cloze', 'Cloze Test'), ('sentence', 'sentence arrangement and logic'), ('synonym_antonym', 'Synonym Antonym Formation'), ('hots', 'HOTS & Olympiad Challenge')], max_length=20)),
                ('question_count', models.PositiveIntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_categories', to='exams.exam')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.RunPython(
            migrate_exam_questions_to_categories, migrations.RunPython.noop
        ),
        migrations.DeleteModel(
            name='ExamQuestion',
        ),
        migrations.AddConstraint(
            model_name='examcategory',
            constraint=models.UniqueConstraint(fields=('exam', 'category'), name='unique_exam_category'),
        ),
        migrations.AddConstraint(
            model_name='examcategory',
            constraint=models.CheckConstraint(condition=models.Q(('question_count__gt', 0)), name='positive_exam_category_question_count'),
        ),
    ]
